'use strict';

// Generated by CoffeeScript 2.3.1
var Currency, PropTypes, React, _;

React = require('react');

PropTypes = require('prop-types');

_ = require('lodash');

Currency = function Currency(props) {
  var n, value;
  if (!_.isFinite(props.children) && _.isEmpty(props.children)) {
    return React.createElement('span', null);
  }
  n = Number(props.children);
  value = n.toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD'
  });
  return React.createElement(
    'span',
    null,
    value
  );
};

Currency.propTypes = {
  children: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
};

module.exports = Currency;