'use strict';

// Generated by CoffeeScript 2.3.1
var ErrorsBlock, PropTypes, React, isEmpty, isString;

React = require('react');

PropTypes = require('prop-types');

var _require = require('lodash');

isEmpty = _require.isEmpty;
isString = _require.isString;


ErrorsBlock = function ErrorsBlock(props) {
  var error, errorStr, errors, errorsDiv, i, msg;
  errors = props.errors;
  error = props.error;

  if (isEmpty(errors) && isEmpty(error)) {
    return React.createElement('span', null);
  }
  errorStr = error && React.createElement(
    'div',
    { className: 'alert alert-danger' },
    error
  ) || React.createElement('span', null);
  errorsDiv = function () {
    var results;
    results = [];
    for (i in errors) {
      msg = errors[i];
      if (!isString(msg)) {
        msg = JSON.stringify(msg);
      }
      results.push(React.createElement(
        'div',
        { key: i, className: 'alert alert-danger' },
        React.createElement(
          'b',
          null,
          i
        ),
        ': ',
        msg
      ));
    }
    return results;
  }();
  return React.createElement(
    'div',
    { style: {
        padding: '1em 0'
      } },
    errorStr,
    errorsDiv
  );
};

ErrorsBlock.propTypes = {
  errors: PropTypes.object,
  error: PropTypes.string
};

module.exports = ErrorsBlock;