'use strict';

// Generated by CoffeeScript 2.3.1
var PropTypes, React, TrEmptyList;

React = require('react');

PropTypes = require('prop-types');

TrEmptyList = function TrEmptyList(props) {
  var colSpan, message;
  colSpan = Number(props.colSpan) || 1;
  message = props.message || 'empty list';
  return React.createElement(
    'tr',
    null,
    React.createElement(
      'td',
      { colSpan: colSpan, className: 'text-center' },
      React.createElement(
        'h5',
        null,
        message
      )
    )
  );
};

TrEmptyList.propTypes = {
  colSpan: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
};

module.exports = TrEmptyList;